#!/bin/bash

echo "========================================="
echo "FlipKit 页面测试与预览"
echo "========================================="
echo ""

echo "应用包名: com.alaikis.flipkit"
echo "APK 位置: build/app/outputs/flutter-apk/app-release.apk"
echo "APK 大小: 195 MB"
echo ""

echo "========================================="
echo "页面列表 (10 个)"
echo "========================================="
echo ""

echo "1. SplashPage (启动页)"
echo "   - 文件: lib/presentation/pages/splash_page.dart"
echo "   - 功能: 应用启动、首次启动判断"
echo "   - 跳转: 首次→OnboardingPage, 否则→HomePage"
echo ""

echo "2. OnboardingPage (引导页)"
echo "   - 文件: lib/presentation/pages/onboarding_page.dart"
echo "   - 功能: 3页引导、功能介绍"
echo "   - 内容: AI组题、OCR识别、资源系统"
echo ""

echo "3. HomePage (主页)"
echo "   - 文件: lib/presentation/pages/home_page.dart"
echo "   - 功能: 学习模块导航、统计展示"
echo "   - 模块: 听写、问答、作文、道法、资源"
echo ""

echo "4. DictationPage (听写页)"
echo "   - 文件: lib/presentation/pages/dictation_page.dart"
echo "   - 功能: AI生成→TTS播放→OCR识别→评分"
echo "   - 流程: 5步 (选择→预览→播放→书写→结果)"
echo ""

echo "5. QuizPage (问答页)"
echo "   - 文件: lib/presentation/pages/quiz_page.dart"
echo "   - 功能: AI生成题目→答题→评分"
echo "   - 题型: 选择题、填空题等"
echo ""

echo "6. EssayPage (作文页)"
echo "   - 文件: lib/presentation/pages/essay_page.dart"
echo "   - 功能: AI生成题目→拍照识别→智能评分"
echo "   - 评分: 总体评价、优点、不足、修改建议"
echo ""

echo "7. DaoismPage (道法页)"
echo "   - 文件: lib/presentation/pages/daoism_page.dart"
echo "   - 功能: 文言文诵读、TTS朗读"
echo "   - 分类: 经典、论语、道德经、金刚经等"
echo ""

echo "8. ResourcePage (资源页)"
echo "   - 文件: lib/presentation/pages/resource_page.dart"
echo "   - 功能: 本地资源、GitHub搜索、网络资源"
echo "   - 标签: 3个 (本地/GitHub/网络)"
echo ""

echo "9. SettingsPage (设置页)"
echo "   - 文件: lib/presentation/pages/settings_page.dart"
echo "   - 功能: 应用设置、账户管理"
echo ""

echo "10. OpensourcePolicyPage (开源政策页)"
echo "   - 文件: lib/presentation/pages/opensource_policy_page.dart"
echo "   - 功能: 开源协议说明、贡献指南"
echo ""

echo "========================================="
echo "技术栈"
echo "========================================="
echo ""
echo "UI 组件: GetWidget 4.0.0"
echo "状态管理: GetX 4.6.6"
echo "动画: flutter_animate 4.3.0"
echo "网络请求: dio 5.4.0"
echo "存储: shared_preferences, get_storage, hive, sqflite"
echo "OCR: google_ml_kit 0.20.0"
echo "TTS: flutter_tts 3.8.3"
echo "WebView: webview_flutter 4.4.2"
echo ""

echo "========================================="
echo "测试建议"
echo "========================================="
echo ""
echo "1. 功能测试:"
echo "   - 测试完整的听写流程 (5步)"
echo "   - 测试问答生成和答题"
echo "   - 测试作文AI评分"
echo "   - 测试道法TTS播放"
echo "   - 测试GitHub资源搜索"
echo ""
echo "2. UI 测试:"
echo "   - 不同屏幕尺寸适配"
echo "   - 深色/浅色主题"
echo "   - 动画流畅度"
echo ""
echo "3. 集成测试:"
echo "   - AI服务调用"
echo "   - OCR识别准确率"
echo "   - TTS播放质量"
echo ""

echo "========================================="
echo "预览方式"
echo "========================================="
echo ""
echo "方式1: 在Android设备上安装APK"
echo "  adb install build/app/outputs/flutter-apk/app-release.apk"
echo ""
echo "方式2: 使用Android模拟器"
echo "  flutter emulators"
echo "  flutter emulators --launch <emulator_id>"
echo "  flutter run"
echo ""
echo "方式3: Web预览 (如果有Chrome)"
echo "  flutter run -d chrome"
echo ""
echo "方式4: 查看代码文档"
echo "  详细内容见: PAGES_PREVIEW.md"
echo ""

echo "========================================="
echo "页面测试命令"
echo "========================================="
echo ""
echo "# 检查代码分析"
echo "flutter analyze"
echo ""
echo "# 运行单元测试"
echo "flutter test"
echo ""
echo "# 构建调试版APK"
echo "flutter build apk --debug"
echo ""
echo "# 构建多架构APK"
echo "flutter build apk --split-per-abi"
echo ""

echo "========================================="
echo "生成时间: $(date)"
echo "========================================="
